### ISSUE TITLE
Bot does not work on Telegram Desktop

### ISSUE THREAD

**Issue by paperbackraita** [GMCtree/Spotify-Bot#4]
Hi,

**Application:** Telegram Desktop
**Version:** v1.0.29

I am not able to see any results for any search query in _both the bot window_ and _the inline search_. Is the bot down?

Attempted searches:
`@spotify_telegram_bot sound of muzak`
`@spotify_telegram_bot track: sound of muzak`
`@spotify_telegram_bot artist: porcupine tree`

**Comment by GMCtree** [comment]
Unfortunately, I am currently not hosting the bot anywhere. I am hoping to eventually get it up and running on a hosting service. Sorry for the inconvenience. I will update the README to notify other users as well.

**Comment by GMCtree** [comment]
I'm going to close this issue and update the README once the bot is live
